# Generated by Django 5.0 on 2023-12-28 09:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1000], upload_to='photos/appkurs', verbose_name='Фото'),
        ),
    ]
