# Generated by Django 5.0 on 2024-01-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkurs', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
