# Generated by Django 5.0 on 2024-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkurs', '0003_student_is_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False, verbose_name='Жив'),
        ),
    ]
