# Generated by Django 5.0 on 2024-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkurs', '0005_alter_student_is_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_dead',
        ),
        migrations.AddField(
            model_name='student',
            name='is_live',
            field=models.BooleanField(default=True, verbose_name='Жив'),
        ),
    ]
