# Generated by Django 5.0 on 2023-12-05 09:40

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprasm', '0003_alter_photoall_photo_alter_photomain_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoall',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1000], upload_to='photos/apprasm/%Y/%m', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photomain',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1000], upload_to='photos/apprasm', verbose_name='Фото'),
        ),
    ]
